### ISSUE TITLE
I just find that the it can't be used in Android default browser

### ISSUE THREAD

**Issue by shenzhuxi** [sa3m/leaflet-control-bing-geocoder#2]
I'm not sure about iOS, because I don't have devices now.  
Here is it. http://ubercheckout.com/

**Comment by sa3m** [comment]
Look at the last merge, maybe it will solve the problem. I am still very far from a computer so I cannot help. Sorry

**Comment by shenzhuxi** [comment]
I checkout the last codes. It seems touchable on Android now.
