### ISSUE TITLE
input textbox on IPad and click button

### ISSUE THREAD

**Issue by geopan** [sa3m/leaflet-control-bing-geocoder#3]
First, thanks for your great job. That works very well on desktop.

However I got a problem on Ipad. I can't input anything inside the text box. I guess that's not because of your code. I have the same problem with a text box inside a custom leaflet control. You might have an idea on how to figure out that.

Cheers

**Comment by sa3m** [comment]
Hey, thank you. It's been a while since I looked at my code so I cannot tell, but maybe some css trick with index or ipad specific css if it exists... I can't help you right now, I am really far away from a real computer. 

Cheers

**Comment by greeninfo** [comment]
A workaround for this was posted by geopan:
https://github.com/CloudMade/Leaflet/issues/1163#issuecomment-10790460
