### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by perliedman** [sa3m/leaflet-control-bing-geocoder#6]
Since I've forked your repository and done some work on it, I'm interested in knowing under what license this code is distributed.

Most Leaflet plugins seem to use BSD 2 clause license, like Leaflet itself. Is this code also under this license?

Sorry if this feels like nitpicking.

**Comment by sa3m** [comment]
I've  never thought about it. Feel free to use it under the same license leaflet uses. Thanks for asking.

Per Liedman notifications@github.com a écrit :

**Comment by perliedman** [comment]
Nice, thanks. I'll update my fork with a LICENSE file.
